### POST request to create contactinfo
POST http://localhost:8000/contactinfos
Content-Type: application/json

{
  "FIRSTNAME": "Elias",
  "LASTNAME": "AdminG",
  "EMAIL": "john.doe@web.de",
  "PHONE": "123456789"
}
