### POST request to create details
POST http://localhost:8000/locations
Content-Type: application/json

{
  "CITY": "Pfalzplatz",
  "ZIPCODE": "18769",
  "STREET": "Kreisel",
  "STREETNUMBER": "3",
  "NAME": "Schön"
}
