POST http://localhost:8000/ctemplates
Content-Type: application/json

{
  "NAME": "contest.NAME.clone()",
  "DESCRIPTION": "contest.DESCRIPTION.clone()",
  "GRADERANGE":" contest.GRADERANGE.clone()",
  "EVALUATION": "contest.EVALUATION.clone()",
  "UNIT": "contest.UNIT.clone()"
}