### POST request to create a pupil
POST http://localhost:8000/pupils
Content-Type: application/json

{
  "firstname": "Elias",
  "lastname": "Doe",
  "password": "testpassword",
  "email": "johndoe@example.com"
}
