### POST request to create details
POST http://localhost:8000/locations
Content-Type: application/json
Cookie: Token=cohofelaejbhpmikblfljkhabhajkhagpgmkekgojjmdccgmeccgdinkcfddebhnjbnkmmameahaiajglpaiplomgkpcimdfjebfhfkfdkbdljmbibncdcbechmimnjjgabmaaaa;

{
  "CITY": "Gau-Algesheim",
  "ZIPCODE": "55435",
  "STREET": "Laurenziberg",
  "STREETNUMBER": "13",
  "NAME": "Old House"
}

### Gau-Algesheim
### 55435
### Laurenziberg
### 13
### Old House