POST http://localhost:8000/sportfests
Content-Type: application/json

{
  "CONTACTPERSON_ID": "f51b0f8e-65ae-4f62-96d4-f357ab12ba83",
  "fest_name": "Sportfest",
  "fest_start": "2024-12-02T15:30:00",
  "fest_end": "2025-12-02T15:30:00",
  "city": "Gau-Algesheim",
  "zip_code": "55435",
  "street": "Laurenziberg",
  "streetnumber": "13",
  "location_name": "Eue"
}
