POST http://localhost:8000/persons/batch
Content-Type: application/json
Cookie: Token=nhllbclochcpgocolfapbnomehdeblhgdmkjbklfbfhidpaampcnfdnlflkckjcpkcjdhbmhpnjiadlncmafjhhbadfiabphphlhgmhblhpapjaambnpcpeeimcmhgdfkebpaaaa

{
  "csv": "FIRSTNAME,LASTNAME,EMAIL@hds,123456789012,1a,1999,admin\nFIRSTNAME,LASTNAME,EMAIL@hdf,123456789012,1a,1999,admin\nFIRSTNAME,LASTNAME,EMAIL@hdfs,123456789012,1a,1999,admin\n"
}
