### POST request to create person
POST http://localhost:8000/persons
Content-Type: application/json

{
  "first_name": "Mama",
  "last_name": "AdminG",
  "email": "johd.doe@web.com",
  "phone": "123456789",
  "role": "ADMIN",
  "grade": "2c"
}
