POST http://localhost:8000/ctemplates
Content-Type: application/json

{
  "NAME": "Wichtiger Wettkampf",
  "DESCRIPTION": "Hier wird gewettkampft",
  "GRADERANGE":"Alle erlaubt",
  "EVALUATION": "ASCENDING",
  "UNIT": "M"
}