POST http://45.81.234.175:8000/sportfests
Content-Type: application/json

{
  "CONTACTPERSON_ID": "893b615d-6f9c-4a40-8398-8e3e3c900431",
  "fest_name": "Sportfest",
  "fest_start": "2024-12-02T15:30:00",
  "fest_end": "2025-12-02T15:30:00",
  "city": "Gau-Algesheim",
  "zip_code": "55435",
  "street": "Laurenziberg",
  "streetnumber": "13",
  "location_name": "Eue"
}
