POST http://45.81.234.175:8000/persons
Content-Type: application/json

{
  "first_name": "Contestant",
  "last_name": "Number20",
  "email": "email20@web.com",
  "phone": "123456789",
  "role": "contestant",
  "grade": "4a",
  "gender": "female",
  "pics": 1,
  "password": "pwd",
  "disabilities": ""
}
