POST http://localhost:8000/contestresults
Content-Type: application/json

{
  "PERSON_ID": "8bfb54c5-7bda-4c63-9dc7-3c124905ca1e",
  "CONTEST_ID": "f888fb77-7d67-4351-a316-70b9f382df36",
  "time" : 10.0
}