POST http://localhost:8000/contests/9bf3e46c-5734-4ad1-9fce-ceeb3bd6a7c9/participants
Cookie: Token=cohofelaejbhpmikblfljkhabhajkhagpgmkekgojjmdccgmeccgdinkcfddebhnjbnkmmameahaiajglpaiplomgkpcimdfjebfhfkfdkbdljmbibncdcbechmimnjjgabmaaaa;
Content-Type: application/json

{
  "participant_ids": ["0f3f032f-1ec3-4dc4-9bf4-c33c0b5b9211"]
}