POST http://localhost:8000/persons/batch
Content-Type: application/json
Cookie: Token=cnpbkglddjlmjekknonfcbnddgcfjpenffgghoajloecgdgenoaegfehifcpoecigaikmodpahhnmiafmbkinbgpklbklkplfjapojnjaimpmgngpmlinhgepahhogifdfhmaaaa

{
  "csv": "Baba,Gabriel,baba@gabriel.de,123456789012\nBaba,Oezcan,baba@oezcan.de,123456789012\nMama,Oezcan,mama@oezcan.de,123456789012\n;\nElias,Oezcan,elias.rw2@gmail.com,123456789012,1a,1999,admin,male,1,baba@oezcan.de,mama@oezcan.de\nElias,Gabriel,elias.gab2@gmail.com,123456789012,1a,1999,admin,male,1,baba@gabriel.de\n"
}
