### POST request to create details
POST http://localhost:8000/details
Content-Type: application/json

{
  "LOCATION_ID": "a3314749-baf2-485c-ba90-7673d7755062",
  "CONTACTPERSON_ID": "127228d9-77e2-478a-abc7-afcf7ef7699c",
  "NAME" : "My Sportfest",
  "START": "2024-12-02T15:30:00",
  "END": "2024-12-02T15:30:00"
}

