### POST request to create details
POST http://localhost:8000/contests
Content-Type: application/json

{
  "SPORTFEST_ID": "51e64f86-e63b-4bc5-9ba7-5bb84de09ee2",
  "DETAILS_ID": "9a2a20fd-c970-4d76-8e77-a173b690432d",
  "NAME": "100m Lauf",
  "ct_name": "Nice template",
  "ct_description": "A nice contest",
  "ct_graderange": "1-4",
  "ct_evaluation": "ASCENDING",
  "ct_unit": "KG"
}

###
# DETAILS_ID: "",
# SPORTFEST_ID: String,
# DETAILS_ID: String,
# NAME: String,
# ct_name: String,
# ct_description: Option<String>,
# ct_graderange: Option<String>,
# ct_evaluation: String,
# ct_unit: String
#