### POST request to create details
POST http://localhost:8000/details
Content-Type: application/json

{
  "LOCATION_ID": "ecfc9f82-cf56-42b8-aa09-60eac58aa4c4",
  "CONTACTPERSON_ID": "0f3f032f-1ec3-4dc4-9bf4-c33c0b5b9211",
  "NAME" : "Super Sportfest",
  "START": "2025-12-02T15:30:00",
  "END": "2025-12-02T15:30:00"
}

