PATCH http://localhost:8000/locations/a4ff5fe5-39ff-4347-adef-c2803d8e6afc
Content-Type: application/json

{
  "NAME": "Elias",
  "CITY": "Dubai",
  "ZIPCODE": "69187",
  "STREET": "Fussballplatz",
  "STREETNUMBER": "13"
}