PATCH http://localhost:8000/contests/b5855ba6-c114-4817-93a3-7bca520f1b11/contestresults
Content-Type: application/json

{
  "results": [
    {
      "p_id": "09f6f219-bc8b-4eb8-93e3-71b657714417",
      "value": 1999.912
    }
  ]
}