POST http://45.81.234.175:8000/register
Content-Type: application/json

{
  "email": "contestant",
  "password": "pwd",

  "first_name": "Elias",
  "last_name": "Contestant",
  "phone": "String",
  "grade": "1a",
  "birth_year": "1999",
  "role": "contestant",
  "gender": "male",
  "pics": 1,
  "disabilities": ""
}