POST http://localhost:8000/register
Content-Type: application/json

{
  "email": "admin",
  "password": "pwd",

  "first_name": "Elias",
  "last_name": "Admin",
  "phone": "String",
  "grade": "1a",
  "birth_year": "1999",
  "role": "admin",
  "gender": "male",
  "pics": 1
}