POST http://localhost:8000/register
Content-Type: application/json

{
  "email": "judge",
  "password": "pwd",

  "first_name": "Elias",
  "last_name": "judgeFr",
  "phone": "String",
  "grade": "Option<String>",
  "birth_year": "Option<String>",
  "role": "Judge",
  "gender": "male",
  "pics": 1
}