mod health;
pub(crate) mod service;
mod sportfest;
mod details;
mod location;
mod person;
mod contest;
mod contestresult;
mod metric;
mod ctemplate;
mod encryption;
pub(crate) mod logon;
mod loggedin;
mod parent_children;
pub(crate) mod general;
mod helper;
pub(crate) mod websocket;
mod photos;