name: CD Pipeline

on:
  push:
    branches:
      - "main" # Trigger only on push events to the main branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancels any previous run of the same workflow

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create .env file
      - name: Create .env file
        run: echo "${{ vars.ENV_FILE_CONTENT }}" > ./Backend/.env

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push Docker images to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/athlead-backend:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/athlead-backend:latest

  start-service:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      # Execute remote SSH commands
      - name: Deploy backend on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Navigate to the deployment directory
            cd /home/${{ secrets.USER }}/athlead-backend

            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/athlead-backend:latest

            # Stop and remove the old container
            sudo docker stop athlead-backend || true
            sudo docker rm athlead-backend || true

            # Run the updated container
            sudo docker run -d \
              --name athlead-backend \
              -p 8080:8080 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/athlead-backend:latest
