name: Deploy Rust Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t athlead-backend .

    - name: Deploy to Server
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
        chmod 600 deploy_key
        eval "$(ssh-agent -a /tmp/ssh_agent.sock)"
        ssh-add deploy_key
        ssh -o StrictHostKeyChecking=no ${{ vars.USER }}@${{ vars.HOST }} << 'EOF'
          docker pull athlead-backend
          docker stop athlead_backend || true
          docker rm athlead_backend || true
          docker run -d --name athlead_backend -p 8080:8080 athlead-backend
        EOF
