name: Deploy Rust Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t AthleadBackend .

    - name: Deploy to Server
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
        chmod 600 deploy_key
        eval "$(ssh-agent -a /tmp/ssh_agent.sock)"
        ssh-add deploy_key
        ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
          docker pull AthleadBackend
          docker stop rust_app || true
          docker rm rust_app || true
          docker run -d --name backend -p 8080:8080 AthleadBackend
        EOF
